kind: ReplicationController
apiVersion: v1
metadata:
  name: hello
  labels:
    name: hello
spec:
  replicas: 1
  selector:
    name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: 20.26.33.121:5000/hello
        resources:
          limits:
            cpu: 600m
            memory: 600Mi
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: SPRING_CONFIG_URI
          value: 'http://ms:Microservice123!@20.26.33.122:32011'
        - name: CONFIG_ACTIVE
          value: "test"
        command: ["sh","-c","java -server -Xms256m -Xmx256m  -Djava.io.tmpdir=/var/tmp -Duser.timezone=Asia/Shanghai -jar hello.jar --spring.profiles.active=${CONFIG_ACTIVE} --server.port=8080 "]
        ports:
        - containerPort: 8080